name: SWGOH TB Tracker

on:
  workflow_dispatch:

jobs:
  tb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Réveiller Comlink
        run: |
          for i in {1..10}; do
            status=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.COMLINK_URL }}/)
            if [ "$status" = "200" ]; then
              echo "siuuuuu API OK !"
              break
            fi
            echo "Tentative $i... c'est long et c'est chiant et ca marche pas"
            sleep 15
          done
      - run: pip install -r requirements.txt
      - run: python tb_tracker.py
        env:
          ALLY_CODE: ${{ secrets.ALLY_CODE }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_TEST }}
          COMLINK_URL: ${{ secrets.COMLINK_URL }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      - run: python tb_sheets.py
        env:
          ALLY_CODE: ${{ secrets.ALLY_CODE }}
          COMLINK_URL: ${{ secrets.COMLINK_URL }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
